apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Busybox
  namespace: argocd
spec:
  project: default
 
  source:
    repoURL: https://github.com/robert-parr/busybox-app-1.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
 
    automated:
      selfHeal: true
      prune: true