apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-config
  namespace: dev
data:
  exec.enabled: "true"
  exec.shells: bash,sh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
  namespace: dev
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  namespace: dev
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
